### ISSUE TITLE
Blank placeholders instead of images

### ISSUE THREAD

**Issue by GreyEarl** [jordenc/image.grabber#8]
I setup a flow to grab an image from IP camera, but the only thing I get is a low-res image of Homey, like a placeholder image. The (jpg) URL works just fine and is locally reachable for Homey. I tried Telegram and the email app. And yes, I used the correct cards to include the image token.

**Comment by jordenc** [comment]
Can you show a screenshot of the flows that you use?

**Comment by GreyEarl** [comment]
Sure thing!

![1](https://user-images.githubusercontent.com/33351068/39897321-0d3894da-54b2-11e8-8fff-c203d6efb808.PNG)

![2](https://user-images.githubusercontent.com/33351068/39897324-0fc95dce-54b2-11e8-8393-b78009f88247.PNG)

And this is the result:
![3](https://user-images.githubusercontent.com/33351068/39897335-1a674228-54b2-11e8-817d-01bf5b8cdb24.PNG)

**Comment by jordenc** [comment]
Can you try with https://www.totallyhosted.nl/img/datacentra/serverius-datacenter_small.jpg if that works for you, instead of the snap.jpeg URL?

It *might* have to do with the .jpeg extension in some way. But maybe we can find out together.

Second test: Does https://www.totallyhosted.nl/img/datacentra/serverius-datacenter_small.jpeg also work? (I copied the file from .jpg to .jpeg)

**Comment by GreyEarl** [comment]
@jordenc Thanks for your support, but it works now ...

Thing was I only tried to execute manual tests, which were failing. So, I thought, why would it work in real life. As it turns out, it does work in real life. I enabled the flow and I just openend the door and I get the correct images. Strange that the testing option does not work though :)

**Comment by jordenc** [comment]
If you execute the first manually, it should also execute the second and then it works. But good that you managed to make it work!
